# Generated by Django 6.0.1 on 2026-01-18 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skills', models.CharField(max_length=255)),
                ('aadhaar_document', models.FileField(upload_to='documents/aadhaar/')),
                ('police_verification', models.FileField(upload_to='documents/police/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maid_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
